// flow-typed signature: 386bdcd615d6c491751128e33bc326ed
// flow-typed version: <<STUB>>/react-native-paper_v^1.2.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-paper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-paper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-paper/src/components/__tests__/BottomNavigation.test' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/__tests__/Portal.test' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/BottomNavigation' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Button' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Card/Card' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Card/CardActions' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Card/CardContent' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Card/CardCover' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Checkbox.ios' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Checkbox' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Dialog/Dialog' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Dialog/DialogActions' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Dialog/DialogContent' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Dialog/DialogScrollArea' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Dialog/DialogTitle' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Divider' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/DrawerItem' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/DrawerSection' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/FAB' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Icon' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Modal' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Paper' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Portal/Portal' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Portal/PortalConsumer' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Portal/PortalHost' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Portal/PortalManager' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Portal/ThemedPortal' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/RadioButton.ios' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/RadioButton' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/SearchBar' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Switch' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/TextInput' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Toolbar/Toolbar' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Toolbar/ToolbarAction' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Toolbar/ToolbarBackAction' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Toolbar/ToolbarContent' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/TouchableIcon' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/TouchableRipple' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Caption' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Headline' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Paragraph' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/StyledText' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Subheading' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Text' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Title' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/core/Provider' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/core/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/core/withTheme' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/index' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/styles/colors' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/styles/DarkTheme' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/styles/DefaultTheme' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/styles/fonts' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/styles/shadow' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-paper/src/components/__tests__/BottomNavigation.test.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/__tests__/BottomNavigation.test'>;
}
declare module 'react-native-paper/src/components/__tests__/Portal.test.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/__tests__/Portal.test'>;
}
declare module 'react-native-paper/src/components/BottomNavigation.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/BottomNavigation'>;
}
declare module 'react-native-paper/src/components/Button.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Button'>;
}
declare module 'react-native-paper/src/components/Card/Card.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Card/Card'>;
}
declare module 'react-native-paper/src/components/Card/CardActions.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Card/CardActions'>;
}
declare module 'react-native-paper/src/components/Card/CardContent.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Card/CardContent'>;
}
declare module 'react-native-paper/src/components/Card/CardCover.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Card/CardCover'>;
}
declare module 'react-native-paper/src/components/Checkbox.ios.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Checkbox.ios'>;
}
declare module 'react-native-paper/src/components/Checkbox.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Checkbox'>;
}
declare module 'react-native-paper/src/components/Dialog/Dialog.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Dialog/Dialog'>;
}
declare module 'react-native-paper/src/components/Dialog/DialogActions.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Dialog/DialogActions'>;
}
declare module 'react-native-paper/src/components/Dialog/DialogContent.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Dialog/DialogContent'>;
}
declare module 'react-native-paper/src/components/Dialog/DialogScrollArea.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Dialog/DialogScrollArea'>;
}
declare module 'react-native-paper/src/components/Dialog/DialogTitle.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Dialog/DialogTitle'>;
}
declare module 'react-native-paper/src/components/Divider.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Divider'>;
}
declare module 'react-native-paper/src/components/DrawerItem.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/DrawerItem'>;
}
declare module 'react-native-paper/src/components/DrawerSection.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/DrawerSection'>;
}
declare module 'react-native-paper/src/components/FAB.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/FAB'>;
}
declare module 'react-native-paper/src/components/Icon.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Icon'>;
}
declare module 'react-native-paper/src/components/Modal.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Modal'>;
}
declare module 'react-native-paper/src/components/Paper.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Paper'>;
}
declare module 'react-native-paper/src/components/Portal/Portal.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Portal/Portal'>;
}
declare module 'react-native-paper/src/components/Portal/PortalConsumer.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Portal/PortalConsumer'>;
}
declare module 'react-native-paper/src/components/Portal/PortalHost.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Portal/PortalHost'>;
}
declare module 'react-native-paper/src/components/Portal/PortalManager.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Portal/PortalManager'>;
}
declare module 'react-native-paper/src/components/Portal/ThemedPortal.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Portal/ThemedPortal'>;
}
declare module 'react-native-paper/src/components/ProgressBar.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/ProgressBar'>;
}
declare module 'react-native-paper/src/components/RadioButton.ios.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/RadioButton.ios'>;
}
declare module 'react-native-paper/src/components/RadioButton.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/RadioButton'>;
}
declare module 'react-native-paper/src/components/SearchBar.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/SearchBar'>;
}
declare module 'react-native-paper/src/components/Switch.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Switch'>;
}
declare module 'react-native-paper/src/components/TextInput.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/TextInput'>;
}
declare module 'react-native-paper/src/components/Toolbar/Toolbar.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Toolbar/Toolbar'>;
}
declare module 'react-native-paper/src/components/Toolbar/ToolbarAction.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Toolbar/ToolbarAction'>;
}
declare module 'react-native-paper/src/components/Toolbar/ToolbarBackAction.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Toolbar/ToolbarBackAction'>;
}
declare module 'react-native-paper/src/components/Toolbar/ToolbarContent.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Toolbar/ToolbarContent'>;
}
declare module 'react-native-paper/src/components/TouchableIcon.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/TouchableIcon'>;
}
declare module 'react-native-paper/src/components/TouchableRipple.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/TouchableRipple'>;
}
declare module 'react-native-paper/src/components/Typography/Caption.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Caption'>;
}
declare module 'react-native-paper/src/components/Typography/Headline.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Headline'>;
}
declare module 'react-native-paper/src/components/Typography/Paragraph.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Paragraph'>;
}
declare module 'react-native-paper/src/components/Typography/StyledText.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/StyledText'>;
}
declare module 'react-native-paper/src/components/Typography/Subheading.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Subheading'>;
}
declare module 'react-native-paper/src/components/Typography/Text.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Text'>;
}
declare module 'react-native-paper/src/components/Typography/Title.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Title'>;
}
declare module 'react-native-paper/src/core/Provider.js' {
  declare module.exports: $Exports<'react-native-paper/src/core/Provider'>;
}
declare module 'react-native-paper/src/core/ThemeProvider.js' {
  declare module.exports: $Exports<'react-native-paper/src/core/ThemeProvider'>;
}
declare module 'react-native-paper/src/core/withTheme.js' {
  declare module.exports: $Exports<'react-native-paper/src/core/withTheme'>;
}
declare module 'react-native-paper/src/index.js' {
  declare module.exports: $Exports<'react-native-paper/src/index'>;
}
declare module 'react-native-paper/src/styles/colors.js' {
  declare module.exports: $Exports<'react-native-paper/src/styles/colors'>;
}
declare module 'react-native-paper/src/styles/DarkTheme.js' {
  declare module.exports: $Exports<'react-native-paper/src/styles/DarkTheme'>;
}
declare module 'react-native-paper/src/styles/DefaultTheme.js' {
  declare module.exports: $Exports<'react-native-paper/src/styles/DefaultTheme'>;
}
declare module 'react-native-paper/src/styles/fonts.js' {
  declare module.exports: $Exports<'react-native-paper/src/styles/fonts'>;
}
declare module 'react-native-paper/src/styles/shadow.js' {
  declare module.exports: $Exports<'react-native-paper/src/styles/shadow'>;
}
declare module 'react-native-paper/src/types.js' {
  declare module.exports: $Exports<'react-native-paper/src/types'>;
}
