// flow-typed signature: 8bc9640c25074cfb90ea11bd2b720915
// flow-typed version: <<STUB>>/react-navigation_v^2.0.0-alpha.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation/src/__tests__/addNavigationHelpers-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/__tests__/getChildEventSubscriber-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/__tests__/NavigationActions-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/__tests__/NavigationContainer-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/__tests__/NavigationStateUtils-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/addNavigationHelpers' {
  declare module.exports: any;
}

declare module 'react-navigation/src/createNavigationContainer' {
  declare module.exports: any;
}

declare module 'react-navigation/src/getChildEventSubscriber' {
  declare module.exports: any;
}

declare module 'react-navigation/src/NavigationActions' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/__tests__/DrawerNavigator-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/__tests__/StackNavigator-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/__tests__/SwitchNavigator-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/__tests__/TabNavigator-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/createDrawerNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/createKeyboardAwareNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/createNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/createStackNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/createSwitchNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/PlatformHelpers.native' {
  declare module.exports: any;
}

declare module 'react-navigation/src/PlatformHelpers.web' {
  declare module.exports: any;
}

declare module 'react-navigation/src/react-navigation' {
  declare module.exports: any;
}

declare module 'react-navigation/src/react-navigation.web' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/createConfigGetter-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/DrawerRouter-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/Routers-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/StackRouter-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/SwitchRouter-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/TabRouter-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/validateRouteConfigMap-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/createConfigGetter' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/DrawerActions' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/DrawerRouter' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/getNavigationActionCreators' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/getScreenForRouteName' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/KeyGenerator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/StackActions' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/StackRouter' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/SwitchRouter' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/TabRouter' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/validateRouteConfigMap' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/validateScreenOptions' {
  declare module.exports: any;
}

declare module 'react-navigation/src/StateUtils' {
  declare module.exports: any;
}

declare module 'react-navigation/src/utils/docsUrl' {
  declare module.exports: any;
}

declare module 'react-navigation/src/utils/getSceneIndicesForInterpolationInputRange' {
  declare module.exports: any;
}

declare module 'react-navigation/src/utils/invariant' {
  declare module.exports: any;
}

declare module 'react-navigation/src/utils/ReactNativeFeatures' {
  declare module.exports: any;
}

declare module 'react-navigation/src/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-navigation/src/utils/withDefaultValue' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/__tests__/NavigationScenesReducer-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/__tests__/TabView-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/__tests__/Transitioner-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/__tests__/withOrientation-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/AnimatedValueSubscription' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Drawer/DrawerNavigatorItems' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Drawer/DrawerScreen' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Drawer/DrawerSidebar' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Drawer/DrawerView' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Header/Header' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Header/HeaderBackButton' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Header/HeaderStyleInterpolator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Header/HeaderTitle' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Header/ModularHeaderBackButton' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/NavigationContext' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/ResourceSavingSceneView' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/ScenesReducer' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/SceneView' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/StackView/createPointerEventsContainer' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/StackView/StackView' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/StackView/StackViewCard' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/StackView/StackViewLayout' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/StackView/StackViewStyleInterpolator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/StackView/StackViewTransitionConfigs' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/SwitchView/SwitchView' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/TouchableItem' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Transitioner' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/withNavigation' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/withNavigationFocus' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/withOrientation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation/src/__tests__/addNavigationHelpers-test.js' {
  declare module.exports: $Exports<'react-navigation/src/__tests__/addNavigationHelpers-test'>;
}
declare module 'react-navigation/src/__tests__/getChildEventSubscriber-test.js' {
  declare module.exports: $Exports<'react-navigation/src/__tests__/getChildEventSubscriber-test'>;
}
declare module 'react-navigation/src/__tests__/NavigationActions-test.js' {
  declare module.exports: $Exports<'react-navigation/src/__tests__/NavigationActions-test'>;
}
declare module 'react-navigation/src/__tests__/NavigationContainer-test.js' {
  declare module.exports: $Exports<'react-navigation/src/__tests__/NavigationContainer-test'>;
}
declare module 'react-navigation/src/__tests__/NavigationStateUtils-test.js' {
  declare module.exports: $Exports<'react-navigation/src/__tests__/NavigationStateUtils-test'>;
}
declare module 'react-navigation/src/addNavigationHelpers.js' {
  declare module.exports: $Exports<'react-navigation/src/addNavigationHelpers'>;
}
declare module 'react-navigation/src/createNavigationContainer.js' {
  declare module.exports: $Exports<'react-navigation/src/createNavigationContainer'>;
}
declare module 'react-navigation/src/getChildEventSubscriber.js' {
  declare module.exports: $Exports<'react-navigation/src/getChildEventSubscriber'>;
}
declare module 'react-navigation/src/NavigationActions.js' {
  declare module.exports: $Exports<'react-navigation/src/NavigationActions'>;
}
declare module 'react-navigation/src/navigators/__tests__/DrawerNavigator-test.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/__tests__/DrawerNavigator-test'>;
}
declare module 'react-navigation/src/navigators/__tests__/StackNavigator-test.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/__tests__/StackNavigator-test'>;
}
declare module 'react-navigation/src/navigators/__tests__/SwitchNavigator-test.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/__tests__/SwitchNavigator-test'>;
}
declare module 'react-navigation/src/navigators/__tests__/TabNavigator-test.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/__tests__/TabNavigator-test'>;
}
declare module 'react-navigation/src/navigators/createDrawerNavigator.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/createDrawerNavigator'>;
}
declare module 'react-navigation/src/navigators/createKeyboardAwareNavigator.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/createKeyboardAwareNavigator'>;
}
declare module 'react-navigation/src/navigators/createNavigator.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/createNavigator'>;
}
declare module 'react-navigation/src/navigators/createStackNavigator.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/createStackNavigator'>;
}
declare module 'react-navigation/src/navigators/createSwitchNavigator.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/createSwitchNavigator'>;
}
declare module 'react-navigation/src/PlatformHelpers.native.js' {
  declare module.exports: $Exports<'react-navigation/src/PlatformHelpers.native'>;
}
declare module 'react-navigation/src/PlatformHelpers.web.js' {
  declare module.exports: $Exports<'react-navigation/src/PlatformHelpers.web'>;
}
declare module 'react-navigation/src/react-navigation.js' {
  declare module.exports: $Exports<'react-navigation/src/react-navigation'>;
}
declare module 'react-navigation/src/react-navigation.web.js' {
  declare module.exports: $Exports<'react-navigation/src/react-navigation.web'>;
}
declare module 'react-navigation/src/routers/__tests__/createConfigGetter-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/createConfigGetter-test'>;
}
declare module 'react-navigation/src/routers/__tests__/DrawerRouter-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/DrawerRouter-test'>;
}
declare module 'react-navigation/src/routers/__tests__/Routers-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/Routers-test'>;
}
declare module 'react-navigation/src/routers/__tests__/StackRouter-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/StackRouter-test'>;
}
declare module 'react-navigation/src/routers/__tests__/SwitchRouter-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/SwitchRouter-test'>;
}
declare module 'react-navigation/src/routers/__tests__/TabRouter-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/TabRouter-test'>;
}
declare module 'react-navigation/src/routers/__tests__/validateRouteConfigMap-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/validateRouteConfigMap-test'>;
}
declare module 'react-navigation/src/routers/createConfigGetter.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/createConfigGetter'>;
}
declare module 'react-navigation/src/routers/DrawerActions.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/DrawerActions'>;
}
declare module 'react-navigation/src/routers/DrawerRouter.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/DrawerRouter'>;
}
declare module 'react-navigation/src/routers/getNavigationActionCreators.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/getNavigationActionCreators'>;
}
declare module 'react-navigation/src/routers/getScreenForRouteName.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/getScreenForRouteName'>;
}
declare module 'react-navigation/src/routers/KeyGenerator.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/KeyGenerator'>;
}
declare module 'react-navigation/src/routers/StackActions.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/StackActions'>;
}
declare module 'react-navigation/src/routers/StackRouter.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/StackRouter'>;
}
declare module 'react-navigation/src/routers/SwitchRouter.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/SwitchRouter'>;
}
declare module 'react-navigation/src/routers/TabRouter.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/TabRouter'>;
}
declare module 'react-navigation/src/routers/validateRouteConfigMap.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/validateRouteConfigMap'>;
}
declare module 'react-navigation/src/routers/validateScreenOptions.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/validateScreenOptions'>;
}
declare module 'react-navigation/src/StateUtils.js' {
  declare module.exports: $Exports<'react-navigation/src/StateUtils'>;
}
declare module 'react-navigation/src/utils/docsUrl.js' {
  declare module.exports: $Exports<'react-navigation/src/utils/docsUrl'>;
}
declare module 'react-navigation/src/utils/getSceneIndicesForInterpolationInputRange.js' {
  declare module.exports: $Exports<'react-navigation/src/utils/getSceneIndicesForInterpolationInputRange'>;
}
declare module 'react-navigation/src/utils/invariant.js' {
  declare module.exports: $Exports<'react-navigation/src/utils/invariant'>;
}
declare module 'react-navigation/src/utils/ReactNativeFeatures.js' {
  declare module.exports: $Exports<'react-navigation/src/utils/ReactNativeFeatures'>;
}
declare module 'react-navigation/src/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-navigation/src/utils/shallowEqual'>;
}
declare module 'react-navigation/src/utils/withDefaultValue.js' {
  declare module.exports: $Exports<'react-navigation/src/utils/withDefaultValue'>;
}
declare module 'react-navigation/src/views/__tests__/NavigationScenesReducer-test.js' {
  declare module.exports: $Exports<'react-navigation/src/views/__tests__/NavigationScenesReducer-test'>;
}
declare module 'react-navigation/src/views/__tests__/TabView-test.js' {
  declare module.exports: $Exports<'react-navigation/src/views/__tests__/TabView-test'>;
}
declare module 'react-navigation/src/views/__tests__/Transitioner-test.js' {
  declare module.exports: $Exports<'react-navigation/src/views/__tests__/Transitioner-test'>;
}
declare module 'react-navigation/src/views/__tests__/withOrientation-test.js' {
  declare module.exports: $Exports<'react-navigation/src/views/__tests__/withOrientation-test'>;
}
declare module 'react-navigation/src/views/AnimatedValueSubscription.js' {
  declare module.exports: $Exports<'react-navigation/src/views/AnimatedValueSubscription'>;
}
declare module 'react-navigation/src/views/Drawer/DrawerNavigatorItems.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Drawer/DrawerNavigatorItems'>;
}
declare module 'react-navigation/src/views/Drawer/DrawerScreen.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Drawer/DrawerScreen'>;
}
declare module 'react-navigation/src/views/Drawer/DrawerSidebar.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Drawer/DrawerSidebar'>;
}
declare module 'react-navigation/src/views/Drawer/DrawerView.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Drawer/DrawerView'>;
}
declare module 'react-navigation/src/views/Header/Header.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Header/Header'>;
}
declare module 'react-navigation/src/views/Header/HeaderBackButton.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Header/HeaderBackButton'>;
}
declare module 'react-navigation/src/views/Header/HeaderStyleInterpolator.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Header/HeaderStyleInterpolator'>;
}
declare module 'react-navigation/src/views/Header/HeaderTitle.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Header/HeaderTitle'>;
}
declare module 'react-navigation/src/views/Header/ModularHeaderBackButton.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Header/ModularHeaderBackButton'>;
}
declare module 'react-navigation/src/views/NavigationContext.js' {
  declare module.exports: $Exports<'react-navigation/src/views/NavigationContext'>;
}
declare module 'react-navigation/src/views/ResourceSavingSceneView.js' {
  declare module.exports: $Exports<'react-navigation/src/views/ResourceSavingSceneView'>;
}
declare module 'react-navigation/src/views/ScenesReducer.js' {
  declare module.exports: $Exports<'react-navigation/src/views/ScenesReducer'>;
}
declare module 'react-navigation/src/views/SceneView.js' {
  declare module.exports: $Exports<'react-navigation/src/views/SceneView'>;
}
declare module 'react-navigation/src/views/StackView/createPointerEventsContainer.js' {
  declare module.exports: $Exports<'react-navigation/src/views/StackView/createPointerEventsContainer'>;
}
declare module 'react-navigation/src/views/StackView/StackView.js' {
  declare module.exports: $Exports<'react-navigation/src/views/StackView/StackView'>;
}
declare module 'react-navigation/src/views/StackView/StackViewCard.js' {
  declare module.exports: $Exports<'react-navigation/src/views/StackView/StackViewCard'>;
}
declare module 'react-navigation/src/views/StackView/StackViewLayout.js' {
  declare module.exports: $Exports<'react-navigation/src/views/StackView/StackViewLayout'>;
}
declare module 'react-navigation/src/views/StackView/StackViewStyleInterpolator.js' {
  declare module.exports: $Exports<'react-navigation/src/views/StackView/StackViewStyleInterpolator'>;
}
declare module 'react-navigation/src/views/StackView/StackViewTransitionConfigs.js' {
  declare module.exports: $Exports<'react-navigation/src/views/StackView/StackViewTransitionConfigs'>;
}
declare module 'react-navigation/src/views/SwitchView/SwitchView.js' {
  declare module.exports: $Exports<'react-navigation/src/views/SwitchView/SwitchView'>;
}
declare module 'react-navigation/src/views/TouchableItem.js' {
  declare module.exports: $Exports<'react-navigation/src/views/TouchableItem'>;
}
declare module 'react-navigation/src/views/Transitioner.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Transitioner'>;
}
declare module 'react-navigation/src/views/withNavigation.js' {
  declare module.exports: $Exports<'react-navigation/src/views/withNavigation'>;
}
declare module 'react-navigation/src/views/withNavigationFocus.js' {
  declare module.exports: $Exports<'react-navigation/src/views/withNavigationFocus'>;
}
declare module 'react-navigation/src/views/withOrientation.js' {
  declare module.exports: $Exports<'react-navigation/src/views/withOrientation'>;
}
