// flow-typed signature: c1ecfe71fbb86c3602b7da3d7c141df1
// flow-typed version: <<STUB>>/expo_v^24.0.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo/AppEntry' {
  declare module.exports: any;
}

declare module 'expo/flow/metro-bundler' {
  declare module.exports: any;
}

declare module 'expo/flow/react-native-gesture-handler' {
  declare module.exports: any;
}

declare module 'expo/src/__mocks__/Constants-development' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/Amplitude-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/AuthSession-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/Constants-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/ErrorRecovery-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/Expo-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/Facebook-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/Font-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/Location-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/Notifications-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/SecureStore-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/Segment-test' {
  declare module.exports: any;
}

declare module 'expo/src/__tests__/WebBrowser-test' {
  declare module.exports: any;
}

declare module 'expo/src/admob/RNAdMobBanner' {
  declare module.exports: any;
}

declare module 'expo/src/admob/RNAdMobInterstitial' {
  declare module.exports: any;
}

declare module 'expo/src/admob/RNAdMobRewarded' {
  declare module.exports: any;
}

declare module 'expo/src/admob/RNPublisherBanner' {
  declare module.exports: any;
}

declare module 'expo/src/Amplitude' {
  declare module.exports: any;
}

declare module 'expo/src/apisAreAvailable' {
  declare module.exports: any;
}

declare module 'expo/src/Asset' {
  declare module.exports: any;
}

declare module 'expo/src/AuthSession' {
  declare module.exports: any;
}

declare module 'expo/src/av/Audio' {
  declare module.exports: any;
}

declare module 'expo/src/av/Audio/Recording' {
  declare module.exports: any;
}

declare module 'expo/src/av/Audio/Sound' {
  declare module.exports: any;
}

declare module 'expo/src/av/AV' {
  declare module.exports: any;
}

declare module 'expo/src/av/Video' {
  declare module.exports: any;
}

declare module 'expo/src/BarCodeScanner.android' {
  declare module.exports: any;
}

declare module 'expo/src/BarCodeScanner.ios' {
  declare module.exports: any;
}

declare module 'expo/src/Brightness' {
  declare module.exports: any;
}

declare module 'expo/src/Camera' {
  declare module.exports: any;
}

declare module 'expo/src/CameraBasedBarCodeScanner' {
  declare module.exports: any;
}

declare module 'expo/src/Constants' {
  declare module.exports: any;
}

declare module 'expo/src/Contacts' {
  declare module.exports: any;
}

declare module 'expo/src/DangerZone' {
  declare module.exports: any;
}

declare module 'expo/src/DocumentPicker' {
  declare module.exports: any;
}

declare module 'expo/src/effects/BlurView.android' {
  declare module.exports: any;
}

declare module 'expo/src/effects/BlurView.ios' {
  declare module.exports: any;
}

declare module 'expo/src/effects/LinearGradient.android' {
  declare module.exports: any;
}

declare module 'expo/src/effects/LinearGradient.ios' {
  declare module.exports: any;
}

declare module 'expo/src/environment/__tests__/validate-test' {
  declare module.exports: any;
}

declare module 'expo/src/environment/logging' {
  declare module.exports: any;
}

declare module 'expo/src/environment/validate' {
  declare module.exports: any;
}

declare module 'expo/src/ErrorRecovery' {
  declare module.exports: any;
}

declare module 'expo/src/Expo' {
  declare module.exports: any;
}

declare module 'expo/src/facebook-ads/AdSettings' {
  declare module.exports: any;
}

declare module 'expo/src/facebook-ads/BannerViewManager' {
  declare module.exports: any;
}

declare module 'expo/src/facebook-ads/index' {
  declare module.exports: any;
}

declare module 'expo/src/facebook-ads/InterstitialAdManager' {
  declare module.exports: any;
}

declare module 'expo/src/facebook-ads/NativeAdsManager' {
  declare module.exports: any;
}

declare module 'expo/src/facebook-ads/withNativeAd' {
  declare module.exports: any;
}

declare module 'expo/src/Facebook' {
  declare module.exports: any;
}

declare module 'expo/src/FaceDetector' {
  declare module.exports: any;
}

declare module 'expo/src/FileSystem' {
  declare module.exports: any;
}

declare module 'expo/src/Fingerprint' {
  declare module.exports: any;
}

declare module 'expo/src/Font' {
  declare module.exports: any;
}

declare module 'expo/src/GLView' {
  declare module.exports: any;
}

declare module 'expo/src/Google' {
  declare module.exports: any;
}

declare module 'expo/src/Icon' {
  declare module.exports: any;
}

declare module 'expo/src/ImageManipulator' {
  declare module.exports: any;
}

declare module 'expo/src/ImagePicker' {
  declare module.exports: any;
}

declare module 'expo/src/IntentLauncherAndroid' {
  declare module.exports: any;
}

declare module 'expo/src/KeepAwake' {
  declare module.exports: any;
}

declare module 'expo/src/launch/AppLoading' {
  declare module.exports: any;
}

declare module 'expo/src/launch/AppLoadingNativeWrapper.android' {
  declare module.exports: any;
}

declare module 'expo/src/launch/AppLoadingNativeWrapper.ios' {
  declare module.exports: any;
}

declare module 'expo/src/launch/registerRootComponent' {
  declare module.exports: any;
}

declare module 'expo/src/launch/RootErrorBoundary' {
  declare module.exports: any;
}

declare module 'expo/src/lib/Queue' {
  declare module.exports: any;
}

declare module 'expo/src/Location' {
  declare module.exports: any;
}

declare module 'expo/src/logs/__tests__/Logs-test' {
  declare module.exports: any;
}

declare module 'expo/src/logs/__tests__/LogSerialization-test' {
  declare module.exports: any;
}

declare module 'expo/src/logs/__tests__/RemoteConsole-test' {
  declare module.exports: any;
}

declare module 'expo/src/logs/__tests__/RemoteLogging-test' {
  declare module.exports: any;
}

declare module 'expo/src/logs/__tests__/RemoteLogs-test' {
  declare module.exports: any;
}

declare module 'expo/src/logs/Logs' {
  declare module.exports: any;
}

declare module 'expo/src/logs/LogSerialization' {
  declare module.exports: any;
}

declare module 'expo/src/logs/RemoteConsole' {
  declare module.exports: any;
}

declare module 'expo/src/logs/RemoteLogging' {
  declare module.exports: any;
}

declare module 'expo/src/modal/Modal' {
  declare module.exports: any;
}

declare module 'expo/src/modal/ModalHost' {
  declare module.exports: any;
}

declare module 'expo/src/modal/ModalImplementation' {
  declare module.exports: any;
}

declare module 'expo/src/modal/PureContainer' {
  declare module.exports: any;
}

declare module 'expo/src/Notifications' {
  declare module.exports: any;
}

declare module 'expo/src/OldBarCodeScanner' {
  declare module.exports: any;
}

declare module 'expo/src/Payments' {
  declare module.exports: any;
}

declare module 'expo/src/Pedometer' {
  declare module.exports: any;
}

declare module 'expo/src/Permissions' {
  declare module.exports: any;
}

declare module 'expo/src/ScreenOrientation' {
  declare module.exports: any;
}

declare module 'expo/src/SecureStore' {
  declare module.exports: any;
}

declare module 'expo/src/Segment' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/__tests__/Accelerometer-test' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/__tests__/DeviceMotion-test' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/__tests__/DeviceSensor-test' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/__tests__/Gyroscope-test' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/__tests__/Magnetometer-test' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/Accelerometer' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/DeviceMotion' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/DeviceSensor' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/Gyroscope' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/Magnetometer' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/MagnetometerUncalibrated' {
  declare module.exports: any;
}

declare module 'expo/src/sensor/ThreeAxisSensor' {
  declare module.exports: any;
}

declare module 'expo/src/Speech' {
  declare module.exports: any;
}

declare module 'expo/src/SQLite' {
  declare module.exports: any;
}

declare module 'expo/src/Svg' {
  declare module.exports: any;
}

declare module 'expo/src/takeSnapshotAsync' {
  declare module.exports: any;
}

declare module 'expo/src/timer/polyfillNextTick' {
  declare module.exports: any;
}

declare module 'expo/src/Util' {
  declare module.exports: any;
}

declare module 'expo/src/WebBrowser' {
  declare module.exports: any;
}

declare module 'expo/tools/hashAssetFiles' {
  declare module.exports: any;
}

declare module 'expo/tools/LogReporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo/AppEntry.js' {
  declare module.exports: $Exports<'expo/AppEntry'>;
}
declare module 'expo/flow/metro-bundler.js' {
  declare module.exports: $Exports<'expo/flow/metro-bundler'>;
}
declare module 'expo/flow/react-native-gesture-handler.js' {
  declare module.exports: $Exports<'expo/flow/react-native-gesture-handler'>;
}
declare module 'expo/src/__mocks__/Constants-development.js' {
  declare module.exports: $Exports<'expo/src/__mocks__/Constants-development'>;
}
declare module 'expo/src/__tests__/Amplitude-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/Amplitude-test'>;
}
declare module 'expo/src/__tests__/AuthSession-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/AuthSession-test'>;
}
declare module 'expo/src/__tests__/Constants-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/Constants-test'>;
}
declare module 'expo/src/__tests__/ErrorRecovery-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/ErrorRecovery-test'>;
}
declare module 'expo/src/__tests__/Expo-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/Expo-test'>;
}
declare module 'expo/src/__tests__/Facebook-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/Facebook-test'>;
}
declare module 'expo/src/__tests__/Font-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/Font-test'>;
}
declare module 'expo/src/__tests__/Location-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/Location-test'>;
}
declare module 'expo/src/__tests__/Notifications-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/Notifications-test'>;
}
declare module 'expo/src/__tests__/SecureStore-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/SecureStore-test'>;
}
declare module 'expo/src/__tests__/Segment-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/Segment-test'>;
}
declare module 'expo/src/__tests__/WebBrowser-test.js' {
  declare module.exports: $Exports<'expo/src/__tests__/WebBrowser-test'>;
}
declare module 'expo/src/admob/RNAdMobBanner.js' {
  declare module.exports: $Exports<'expo/src/admob/RNAdMobBanner'>;
}
declare module 'expo/src/admob/RNAdMobInterstitial.js' {
  declare module.exports: $Exports<'expo/src/admob/RNAdMobInterstitial'>;
}
declare module 'expo/src/admob/RNAdMobRewarded.js' {
  declare module.exports: $Exports<'expo/src/admob/RNAdMobRewarded'>;
}
declare module 'expo/src/admob/RNPublisherBanner.js' {
  declare module.exports: $Exports<'expo/src/admob/RNPublisherBanner'>;
}
declare module 'expo/src/Amplitude.js' {
  declare module.exports: $Exports<'expo/src/Amplitude'>;
}
declare module 'expo/src/apisAreAvailable.js' {
  declare module.exports: $Exports<'expo/src/apisAreAvailable'>;
}
declare module 'expo/src/Asset.js' {
  declare module.exports: $Exports<'expo/src/Asset'>;
}
declare module 'expo/src/AuthSession.js' {
  declare module.exports: $Exports<'expo/src/AuthSession'>;
}
declare module 'expo/src/av/Audio.js' {
  declare module.exports: $Exports<'expo/src/av/Audio'>;
}
declare module 'expo/src/av/Audio/Recording.js' {
  declare module.exports: $Exports<'expo/src/av/Audio/Recording'>;
}
declare module 'expo/src/av/Audio/Sound.js' {
  declare module.exports: $Exports<'expo/src/av/Audio/Sound'>;
}
declare module 'expo/src/av/AV.js' {
  declare module.exports: $Exports<'expo/src/av/AV'>;
}
declare module 'expo/src/av/Video.js' {
  declare module.exports: $Exports<'expo/src/av/Video'>;
}
declare module 'expo/src/BarCodeScanner.android.js' {
  declare module.exports: $Exports<'expo/src/BarCodeScanner.android'>;
}
declare module 'expo/src/BarCodeScanner.ios.js' {
  declare module.exports: $Exports<'expo/src/BarCodeScanner.ios'>;
}
declare module 'expo/src/Brightness.js' {
  declare module.exports: $Exports<'expo/src/Brightness'>;
}
declare module 'expo/src/Camera.js' {
  declare module.exports: $Exports<'expo/src/Camera'>;
}
declare module 'expo/src/CameraBasedBarCodeScanner.js' {
  declare module.exports: $Exports<'expo/src/CameraBasedBarCodeScanner'>;
}
declare module 'expo/src/Constants.js' {
  declare module.exports: $Exports<'expo/src/Constants'>;
}
declare module 'expo/src/Contacts.js' {
  declare module.exports: $Exports<'expo/src/Contacts'>;
}
declare module 'expo/src/DangerZone.js' {
  declare module.exports: $Exports<'expo/src/DangerZone'>;
}
declare module 'expo/src/DocumentPicker.js' {
  declare module.exports: $Exports<'expo/src/DocumentPicker'>;
}
declare module 'expo/src/effects/BlurView.android.js' {
  declare module.exports: $Exports<'expo/src/effects/BlurView.android'>;
}
declare module 'expo/src/effects/BlurView.ios.js' {
  declare module.exports: $Exports<'expo/src/effects/BlurView.ios'>;
}
declare module 'expo/src/effects/LinearGradient.android.js' {
  declare module.exports: $Exports<'expo/src/effects/LinearGradient.android'>;
}
declare module 'expo/src/effects/LinearGradient.ios.js' {
  declare module.exports: $Exports<'expo/src/effects/LinearGradient.ios'>;
}
declare module 'expo/src/environment/__tests__/validate-test.js' {
  declare module.exports: $Exports<'expo/src/environment/__tests__/validate-test'>;
}
declare module 'expo/src/environment/logging.js' {
  declare module.exports: $Exports<'expo/src/environment/logging'>;
}
declare module 'expo/src/environment/validate.js' {
  declare module.exports: $Exports<'expo/src/environment/validate'>;
}
declare module 'expo/src/ErrorRecovery.js' {
  declare module.exports: $Exports<'expo/src/ErrorRecovery'>;
}
declare module 'expo/src/Expo.js' {
  declare module.exports: $Exports<'expo/src/Expo'>;
}
declare module 'expo/src/facebook-ads/AdSettings.js' {
  declare module.exports: $Exports<'expo/src/facebook-ads/AdSettings'>;
}
declare module 'expo/src/facebook-ads/BannerViewManager.js' {
  declare module.exports: $Exports<'expo/src/facebook-ads/BannerViewManager'>;
}
declare module 'expo/src/facebook-ads/index.js' {
  declare module.exports: $Exports<'expo/src/facebook-ads/index'>;
}
declare module 'expo/src/facebook-ads/InterstitialAdManager.js' {
  declare module.exports: $Exports<'expo/src/facebook-ads/InterstitialAdManager'>;
}
declare module 'expo/src/facebook-ads/NativeAdsManager.js' {
  declare module.exports: $Exports<'expo/src/facebook-ads/NativeAdsManager'>;
}
declare module 'expo/src/facebook-ads/withNativeAd.js' {
  declare module.exports: $Exports<'expo/src/facebook-ads/withNativeAd'>;
}
declare module 'expo/src/Facebook.js' {
  declare module.exports: $Exports<'expo/src/Facebook'>;
}
declare module 'expo/src/FaceDetector.js' {
  declare module.exports: $Exports<'expo/src/FaceDetector'>;
}
declare module 'expo/src/FileSystem.js' {
  declare module.exports: $Exports<'expo/src/FileSystem'>;
}
declare module 'expo/src/Fingerprint.js' {
  declare module.exports: $Exports<'expo/src/Fingerprint'>;
}
declare module 'expo/src/Font.js' {
  declare module.exports: $Exports<'expo/src/Font'>;
}
declare module 'expo/src/GLView.js' {
  declare module.exports: $Exports<'expo/src/GLView'>;
}
declare module 'expo/src/Google.js' {
  declare module.exports: $Exports<'expo/src/Google'>;
}
declare module 'expo/src/Icon.js' {
  declare module.exports: $Exports<'expo/src/Icon'>;
}
declare module 'expo/src/ImageManipulator.js' {
  declare module.exports: $Exports<'expo/src/ImageManipulator'>;
}
declare module 'expo/src/ImagePicker.js' {
  declare module.exports: $Exports<'expo/src/ImagePicker'>;
}
declare module 'expo/src/IntentLauncherAndroid.js' {
  declare module.exports: $Exports<'expo/src/IntentLauncherAndroid'>;
}
declare module 'expo/src/KeepAwake.js' {
  declare module.exports: $Exports<'expo/src/KeepAwake'>;
}
declare module 'expo/src/launch/AppLoading.js' {
  declare module.exports: $Exports<'expo/src/launch/AppLoading'>;
}
declare module 'expo/src/launch/AppLoadingNativeWrapper.android.js' {
  declare module.exports: $Exports<'expo/src/launch/AppLoadingNativeWrapper.android'>;
}
declare module 'expo/src/launch/AppLoadingNativeWrapper.ios.js' {
  declare module.exports: $Exports<'expo/src/launch/AppLoadingNativeWrapper.ios'>;
}
declare module 'expo/src/launch/registerRootComponent.js' {
  declare module.exports: $Exports<'expo/src/launch/registerRootComponent'>;
}
declare module 'expo/src/launch/RootErrorBoundary.js' {
  declare module.exports: $Exports<'expo/src/launch/RootErrorBoundary'>;
}
declare module 'expo/src/lib/Queue.js' {
  declare module.exports: $Exports<'expo/src/lib/Queue'>;
}
declare module 'expo/src/Location.js' {
  declare module.exports: $Exports<'expo/src/Location'>;
}
declare module 'expo/src/logs/__tests__/Logs-test.js' {
  declare module.exports: $Exports<'expo/src/logs/__tests__/Logs-test'>;
}
declare module 'expo/src/logs/__tests__/LogSerialization-test.js' {
  declare module.exports: $Exports<'expo/src/logs/__tests__/LogSerialization-test'>;
}
declare module 'expo/src/logs/__tests__/RemoteConsole-test.js' {
  declare module.exports: $Exports<'expo/src/logs/__tests__/RemoteConsole-test'>;
}
declare module 'expo/src/logs/__tests__/RemoteLogging-test.js' {
  declare module.exports: $Exports<'expo/src/logs/__tests__/RemoteLogging-test'>;
}
declare module 'expo/src/logs/__tests__/RemoteLogs-test.js' {
  declare module.exports: $Exports<'expo/src/logs/__tests__/RemoteLogs-test'>;
}
declare module 'expo/src/logs/Logs.js' {
  declare module.exports: $Exports<'expo/src/logs/Logs'>;
}
declare module 'expo/src/logs/LogSerialization.js' {
  declare module.exports: $Exports<'expo/src/logs/LogSerialization'>;
}
declare module 'expo/src/logs/RemoteConsole.js' {
  declare module.exports: $Exports<'expo/src/logs/RemoteConsole'>;
}
declare module 'expo/src/logs/RemoteLogging.js' {
  declare module.exports: $Exports<'expo/src/logs/RemoteLogging'>;
}
declare module 'expo/src/modal/Modal.js' {
  declare module.exports: $Exports<'expo/src/modal/Modal'>;
}
declare module 'expo/src/modal/ModalHost.js' {
  declare module.exports: $Exports<'expo/src/modal/ModalHost'>;
}
declare module 'expo/src/modal/ModalImplementation.js' {
  declare module.exports: $Exports<'expo/src/modal/ModalImplementation'>;
}
declare module 'expo/src/modal/PureContainer.js' {
  declare module.exports: $Exports<'expo/src/modal/PureContainer'>;
}
declare module 'expo/src/Notifications.js' {
  declare module.exports: $Exports<'expo/src/Notifications'>;
}
declare module 'expo/src/OldBarCodeScanner.js' {
  declare module.exports: $Exports<'expo/src/OldBarCodeScanner'>;
}
declare module 'expo/src/Payments.js' {
  declare module.exports: $Exports<'expo/src/Payments'>;
}
declare module 'expo/src/Pedometer.js' {
  declare module.exports: $Exports<'expo/src/Pedometer'>;
}
declare module 'expo/src/Permissions.js' {
  declare module.exports: $Exports<'expo/src/Permissions'>;
}
declare module 'expo/src/ScreenOrientation.js' {
  declare module.exports: $Exports<'expo/src/ScreenOrientation'>;
}
declare module 'expo/src/SecureStore.js' {
  declare module.exports: $Exports<'expo/src/SecureStore'>;
}
declare module 'expo/src/Segment.js' {
  declare module.exports: $Exports<'expo/src/Segment'>;
}
declare module 'expo/src/sensor/__tests__/Accelerometer-test.js' {
  declare module.exports: $Exports<'expo/src/sensor/__tests__/Accelerometer-test'>;
}
declare module 'expo/src/sensor/__tests__/DeviceMotion-test.js' {
  declare module.exports: $Exports<'expo/src/sensor/__tests__/DeviceMotion-test'>;
}
declare module 'expo/src/sensor/__tests__/DeviceSensor-test.js' {
  declare module.exports: $Exports<'expo/src/sensor/__tests__/DeviceSensor-test'>;
}
declare module 'expo/src/sensor/__tests__/Gyroscope-test.js' {
  declare module.exports: $Exports<'expo/src/sensor/__tests__/Gyroscope-test'>;
}
declare module 'expo/src/sensor/__tests__/Magnetometer-test.js' {
  declare module.exports: $Exports<'expo/src/sensor/__tests__/Magnetometer-test'>;
}
declare module 'expo/src/sensor/Accelerometer.js' {
  declare module.exports: $Exports<'expo/src/sensor/Accelerometer'>;
}
declare module 'expo/src/sensor/DeviceMotion.js' {
  declare module.exports: $Exports<'expo/src/sensor/DeviceMotion'>;
}
declare module 'expo/src/sensor/DeviceSensor.js' {
  declare module.exports: $Exports<'expo/src/sensor/DeviceSensor'>;
}
declare module 'expo/src/sensor/Gyroscope.js' {
  declare module.exports: $Exports<'expo/src/sensor/Gyroscope'>;
}
declare module 'expo/src/sensor/Magnetometer.js' {
  declare module.exports: $Exports<'expo/src/sensor/Magnetometer'>;
}
declare module 'expo/src/sensor/MagnetometerUncalibrated.js' {
  declare module.exports: $Exports<'expo/src/sensor/MagnetometerUncalibrated'>;
}
declare module 'expo/src/sensor/ThreeAxisSensor.js' {
  declare module.exports: $Exports<'expo/src/sensor/ThreeAxisSensor'>;
}
declare module 'expo/src/Speech.js' {
  declare module.exports: $Exports<'expo/src/Speech'>;
}
declare module 'expo/src/SQLite.js' {
  declare module.exports: $Exports<'expo/src/SQLite'>;
}
declare module 'expo/src/Svg.js' {
  declare module.exports: $Exports<'expo/src/Svg'>;
}
declare module 'expo/src/takeSnapshotAsync.js' {
  declare module.exports: $Exports<'expo/src/takeSnapshotAsync'>;
}
declare module 'expo/src/timer/polyfillNextTick.js' {
  declare module.exports: $Exports<'expo/src/timer/polyfillNextTick'>;
}
declare module 'expo/src/Util.js' {
  declare module.exports: $Exports<'expo/src/Util'>;
}
declare module 'expo/src/WebBrowser.js' {
  declare module.exports: $Exports<'expo/src/WebBrowser'>;
}
declare module 'expo/tools/hashAssetFiles.js' {
  declare module.exports: $Exports<'expo/tools/hashAssetFiles'>;
}
declare module 'expo/tools/LogReporter.js' {
  declare module.exports: $Exports<'expo/tools/LogReporter'>;
}
