// flow-typed signature: 42d8cd2e84e894c09d28f891fef9f01d
// flow-typed version: <<STUB>>/react-native-scripts_v^1.5.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-scripts/build/bin/crna-entry' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/bin/react-native-scripts' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/scripts/android' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/scripts/eject' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/scripts/init' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/scripts/ios' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/scripts/start' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/util/clearConsole' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/util/expo' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/util/install' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/util/log' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/util/packager' {
  declare module.exports: any;
}

declare module 'react-native-scripts/template/App' {
  declare module.exports: any;
}

declare module 'react-native-scripts/template/App.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-scripts/build/bin/crna-entry.js' {
  declare module.exports: $Exports<'react-native-scripts/build/bin/crna-entry'>;
}
declare module 'react-native-scripts/build/bin/react-native-scripts.js' {
  declare module.exports: $Exports<'react-native-scripts/build/bin/react-native-scripts'>;
}
declare module 'react-native-scripts/build/scripts/android.js' {
  declare module.exports: $Exports<'react-native-scripts/build/scripts/android'>;
}
declare module 'react-native-scripts/build/scripts/eject.js' {
  declare module.exports: $Exports<'react-native-scripts/build/scripts/eject'>;
}
declare module 'react-native-scripts/build/scripts/init.js' {
  declare module.exports: $Exports<'react-native-scripts/build/scripts/init'>;
}
declare module 'react-native-scripts/build/scripts/ios.js' {
  declare module.exports: $Exports<'react-native-scripts/build/scripts/ios'>;
}
declare module 'react-native-scripts/build/scripts/start.js' {
  declare module.exports: $Exports<'react-native-scripts/build/scripts/start'>;
}
declare module 'react-native-scripts/build/util/clearConsole.js' {
  declare module.exports: $Exports<'react-native-scripts/build/util/clearConsole'>;
}
declare module 'react-native-scripts/build/util/expo.js' {
  declare module.exports: $Exports<'react-native-scripts/build/util/expo'>;
}
declare module 'react-native-scripts/build/util/install.js' {
  declare module.exports: $Exports<'react-native-scripts/build/util/install'>;
}
declare module 'react-native-scripts/build/util/log.js' {
  declare module.exports: $Exports<'react-native-scripts/build/util/log'>;
}
declare module 'react-native-scripts/build/util/packager.js' {
  declare module.exports: $Exports<'react-native-scripts/build/util/packager'>;
}
declare module 'react-native-scripts/template/App.js' {
  declare module.exports: $Exports<'react-native-scripts/template/App'>;
}
declare module 'react-native-scripts/template/App.test.js' {
  declare module.exports: $Exports<'react-native-scripts/template/App.test'>;
}
