
[build]
  base    = "/"
  publish = "example/web-build"
  command = "yarn example expo export:web"
  environment = { YARN_VERSION = "3.2.2" }

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
