packages:
  - packages/*
  - example
allowBuilds:
  '@evilmartians/lefthook': true
  core-js: false
  esbuild: false
  unrs-resolver: false
patchedDependencies:
  react-native-screens@4.26.2: patches/react-native-screens@4.26.2.patch
