packages:
  - packages/*
  - example
allowBuilds:
  '@evilmartians/lefthook': true
  core-js: false
  esbuild: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@typescript/typescript-aix-ppc64@7.0.1-rc'
  - '@typescript/typescript-darwin-arm64@7.0.1-rc'
  - '@typescript/typescript-darwin-x64@7.0.1-rc'
  - '@typescript/typescript-freebsd-arm64@7.0.1-rc'
  - '@typescript/typescript-freebsd-x64@7.0.1-rc'
  - '@typescript/typescript-linux-arm64@7.0.1-rc'
  - '@typescript/typescript-linux-arm@7.0.1-rc'
  - '@typescript/typescript-linux-loong64@7.0.1-rc'
  - '@typescript/typescript-linux-mips64el@7.0.1-rc'
  - '@typescript/typescript-linux-ppc64@7.0.1-rc'
  - '@typescript/typescript-linux-riscv64@7.0.1-rc'
  - '@typescript/typescript-linux-s390x@7.0.1-rc'
  - '@typescript/typescript-linux-x64@7.0.1-rc'
  - '@typescript/typescript-netbsd-arm64@7.0.1-rc'
  - '@typescript/typescript-netbsd-x64@7.0.1-rc'
  - '@typescript/typescript-openbsd-arm64@7.0.1-rc'
  - '@typescript/typescript-openbsd-x64@7.0.1-rc'
  - '@typescript/typescript-sunos-x64@7.0.1-rc'
  - '@typescript/typescript-win32-arm64@7.0.1-rc'
  - '@typescript/typescript-win32-x64@7.0.1-rc'
  - typescript@7.0.1-rc
