// flow-typed signature: 48213b3a96834e8c0012431509c578e1
// flow-typed version: <<STUB>>/babel-preset-react-native_v^2.1.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-react-native/configs/hmr' {
  declare module.exports: any;
}

declare module 'babel-preset-react-native/configs/internal' {
  declare module.exports: any;
}

declare module 'babel-preset-react-native/configs/main' {
  declare module.exports: any;
}

declare module 'babel-preset-react-native/lib/resolvePlugins' {
  declare module.exports: any;
}

declare module 'babel-preset-react-native/plugins' {
  declare module.exports: any;
}

declare module 'babel-preset-react-native/transforms/transform-regenerator-runtime-insertion' {
  declare module.exports: any;
}

declare module 'babel-preset-react-native/transforms/transform-symbol-member' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-react-native/configs/hmr.js' {
  declare module.exports: $Exports<'babel-preset-react-native/configs/hmr'>;
}
declare module 'babel-preset-react-native/configs/internal.js' {
  declare module.exports: $Exports<'babel-preset-react-native/configs/internal'>;
}
declare module 'babel-preset-react-native/configs/main.js' {
  declare module.exports: $Exports<'babel-preset-react-native/configs/main'>;
}
declare module 'babel-preset-react-native/index' {
  declare module.exports: $Exports<'babel-preset-react-native'>;
}
declare module 'babel-preset-react-native/index.js' {
  declare module.exports: $Exports<'babel-preset-react-native'>;
}
declare module 'babel-preset-react-native/lib/resolvePlugins.js' {
  declare module.exports: $Exports<'babel-preset-react-native/lib/resolvePlugins'>;
}
declare module 'babel-preset-react-native/plugins.js' {
  declare module.exports: $Exports<'babel-preset-react-native/plugins'>;
}
declare module 'babel-preset-react-native/transforms/transform-regenerator-runtime-insertion.js' {
  declare module.exports: $Exports<'babel-preset-react-native/transforms/transform-regenerator-runtime-insertion'>;
}
declare module 'babel-preset-react-native/transforms/transform-symbol-member.js' {
  declare module.exports: $Exports<'babel-preset-react-native/transforms/transform-symbol-member'>;
}
