// flow-typed signature: 7242cc9c9c438ae2e520190a20aae5ce
// flow-typed version: <<STUB>>/babel-preset-react-native-stage-0_v^1.0.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-native-stage-0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-native-stage-0' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-react-native-stage-0/decorator-support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-react-native-stage-0/decorator-support.js' {
  declare module.exports: $Exports<'babel-preset-react-native-stage-0/decorator-support'>;
}
declare module 'babel-preset-react-native-stage-0/index' {
  declare module.exports: $Exports<'babel-preset-react-native-stage-0'>;
}
declare module 'babel-preset-react-native-stage-0/index.js' {
  declare module.exports: $Exports<'babel-preset-react-native-stage-0'>;
}
