// flow-typed signature: 57c87eb1fb3b55786881f12b604fa66a
// flow-typed version: <<STUB>>/babel-preset-react-native-syntax_v^1.0.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-native-syntax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-native-syntax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-react-native-syntax/index' {
  declare module.exports: $Exports<'babel-preset-react-native-syntax'>;
}
declare module 'babel-preset-react-native-syntax/index.js' {
  declare module.exports: $Exports<'babel-preset-react-native-syntax'>;
}
