// flow-typed signature: a670b876b547d1b25ef0424c268358a4
// flow-typed version: <<STUB>>/babel-plugin-transform-define_v^1.3.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-define'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-define' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-define/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/0/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/0/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/emptyString/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/emptyString/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/false/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/false/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/identifier/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/identifier/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/load-config-file/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/load-config-file/config' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/load-config-file/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/member-expression/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/member-expression/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/null/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/null/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/unary-expression/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/unary-expression/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/undefined/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-define/test/undefined/expected' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-define/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/lib/index'>;
}
declare module 'babel-plugin-transform-define/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/src/index'>;
}
declare module 'babel-plugin-transform-define/test/0/actual.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/0/actual'>;
}
declare module 'babel-plugin-transform-define/test/0/expected.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/0/expected'>;
}
declare module 'babel-plugin-transform-define/test/emptyString/actual.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/emptyString/actual'>;
}
declare module 'babel-plugin-transform-define/test/emptyString/expected.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/emptyString/expected'>;
}
declare module 'babel-plugin-transform-define/test/false/actual.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/false/actual'>;
}
declare module 'babel-plugin-transform-define/test/false/expected.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/false/expected'>;
}
declare module 'babel-plugin-transform-define/test/identifier/actual.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/identifier/actual'>;
}
declare module 'babel-plugin-transform-define/test/identifier/expected.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/identifier/expected'>;
}
declare module 'babel-plugin-transform-define/test/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/index'>;
}
declare module 'babel-plugin-transform-define/test/load-config-file/actual.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/load-config-file/actual'>;
}
declare module 'babel-plugin-transform-define/test/load-config-file/config.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/load-config-file/config'>;
}
declare module 'babel-plugin-transform-define/test/load-config-file/expected.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/load-config-file/expected'>;
}
declare module 'babel-plugin-transform-define/test/member-expression/actual.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/member-expression/actual'>;
}
declare module 'babel-plugin-transform-define/test/member-expression/expected.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/member-expression/expected'>;
}
declare module 'babel-plugin-transform-define/test/null/actual.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/null/actual'>;
}
declare module 'babel-plugin-transform-define/test/null/expected.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/null/expected'>;
}
declare module 'babel-plugin-transform-define/test/unary-expression/actual.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/unary-expression/actual'>;
}
declare module 'babel-plugin-transform-define/test/unary-expression/expected.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/unary-expression/expected'>;
}
declare module 'babel-plugin-transform-define/test/undefined/actual.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/undefined/actual'>;
}
declare module 'babel-plugin-transform-define/test/undefined/expected.js' {
  declare module.exports: $Exports<'babel-plugin-transform-define/test/undefined/expected'>;
}
