// flow-typed signature: 5d53c1dc058e8864450c1d7f101839c4
// flow-typed version: <<STUB>>/clamp_v^1.0.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clamp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clamp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clamp/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clamp/index' {
  declare module.exports: $Exports<'clamp'>;
}
declare module 'clamp/index.js' {
  declare module.exports: $Exports<'clamp'>;
}
declare module 'clamp/test.js' {
  declare module.exports: $Exports<'clamp/test'>;
}
