// flow-typed signature: ad1840bbbf16a47effbbfa3f63f45a8d
// flow-typed version: <<STUB>>/codecov_v^2.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codecov'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codecov' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codecov/lib/codecov' {
  declare module.exports: any;
}

declare module 'codecov/lib/detect' {
  declare module.exports: any;
}

declare module 'codecov/lib/git' {
  declare module.exports: any;
}

declare module 'codecov/lib/offline' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/appveyor' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/buildkite' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/circle' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/codeship' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/drone' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/gitlab' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/jenkins' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/localGit' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/semaphore' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/shippable' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/snap' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/travis' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/wercker' {
  declare module.exports: any;
}

declare module 'codecov/test/detect' {
  declare module.exports: any;
}

declare module 'codecov/test/git' {
  declare module.exports: any;
}

declare module 'codecov/test/index' {
  declare module.exports: any;
}

declare module 'codecov/test/services/appveyor' {
  declare module.exports: any;
}

declare module 'codecov/test/services/buildkite' {
  declare module.exports: any;
}

declare module 'codecov/test/services/circle' {
  declare module.exports: any;
}

declare module 'codecov/test/services/codeship' {
  declare module.exports: any;
}

declare module 'codecov/test/services/drone' {
  declare module.exports: any;
}

declare module 'codecov/test/services/gitlab' {
  declare module.exports: any;
}

declare module 'codecov/test/services/jenkins' {
  declare module.exports: any;
}

declare module 'codecov/test/services/localGit' {
  declare module.exports: any;
}

declare module 'codecov/test/services/semaphore' {
  declare module.exports: any;
}

declare module 'codecov/test/services/shippable' {
  declare module.exports: any;
}

declare module 'codecov/test/services/snap' {
  declare module.exports: any;
}

declare module 'codecov/test/services/travis' {
  declare module.exports: any;
}

declare module 'codecov/test/services/wercker' {
  declare module.exports: any;
}

declare module 'codecov/test/upload' {
  declare module.exports: any;
}

declare module 'codecov/testinit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codecov/index' {
  declare module.exports: $Exports<'codecov'>;
}
declare module 'codecov/index.js' {
  declare module.exports: $Exports<'codecov'>;
}
declare module 'codecov/lib/codecov.js' {
  declare module.exports: $Exports<'codecov/lib/codecov'>;
}
declare module 'codecov/lib/detect.js' {
  declare module.exports: $Exports<'codecov/lib/detect'>;
}
declare module 'codecov/lib/git.js' {
  declare module.exports: $Exports<'codecov/lib/git'>;
}
declare module 'codecov/lib/offline.js' {
  declare module.exports: $Exports<'codecov/lib/offline'>;
}
declare module 'codecov/lib/services/appveyor.js' {
  declare module.exports: $Exports<'codecov/lib/services/appveyor'>;
}
declare module 'codecov/lib/services/buildkite.js' {
  declare module.exports: $Exports<'codecov/lib/services/buildkite'>;
}
declare module 'codecov/lib/services/circle.js' {
  declare module.exports: $Exports<'codecov/lib/services/circle'>;
}
declare module 'codecov/lib/services/codeship.js' {
  declare module.exports: $Exports<'codecov/lib/services/codeship'>;
}
declare module 'codecov/lib/services/drone.js' {
  declare module.exports: $Exports<'codecov/lib/services/drone'>;
}
declare module 'codecov/lib/services/gitlab.js' {
  declare module.exports: $Exports<'codecov/lib/services/gitlab'>;
}
declare module 'codecov/lib/services/jenkins.js' {
  declare module.exports: $Exports<'codecov/lib/services/jenkins'>;
}
declare module 'codecov/lib/services/localGit.js' {
  declare module.exports: $Exports<'codecov/lib/services/localGit'>;
}
declare module 'codecov/lib/services/semaphore.js' {
  declare module.exports: $Exports<'codecov/lib/services/semaphore'>;
}
declare module 'codecov/lib/services/shippable.js' {
  declare module.exports: $Exports<'codecov/lib/services/shippable'>;
}
declare module 'codecov/lib/services/snap.js' {
  declare module.exports: $Exports<'codecov/lib/services/snap'>;
}
declare module 'codecov/lib/services/travis.js' {
  declare module.exports: $Exports<'codecov/lib/services/travis'>;
}
declare module 'codecov/lib/services/wercker.js' {
  declare module.exports: $Exports<'codecov/lib/services/wercker'>;
}
declare module 'codecov/test/detect.js' {
  declare module.exports: $Exports<'codecov/test/detect'>;
}
declare module 'codecov/test/git.js' {
  declare module.exports: $Exports<'codecov/test/git'>;
}
declare module 'codecov/test/index.js' {
  declare module.exports: $Exports<'codecov/test/index'>;
}
declare module 'codecov/test/services/appveyor.js' {
  declare module.exports: $Exports<'codecov/test/services/appveyor'>;
}
declare module 'codecov/test/services/buildkite.js' {
  declare module.exports: $Exports<'codecov/test/services/buildkite'>;
}
declare module 'codecov/test/services/circle.js' {
  declare module.exports: $Exports<'codecov/test/services/circle'>;
}
declare module 'codecov/test/services/codeship.js' {
  declare module.exports: $Exports<'codecov/test/services/codeship'>;
}
declare module 'codecov/test/services/drone.js' {
  declare module.exports: $Exports<'codecov/test/services/drone'>;
}
declare module 'codecov/test/services/gitlab.js' {
  declare module.exports: $Exports<'codecov/test/services/gitlab'>;
}
declare module 'codecov/test/services/jenkins.js' {
  declare module.exports: $Exports<'codecov/test/services/jenkins'>;
}
declare module 'codecov/test/services/localGit.js' {
  declare module.exports: $Exports<'codecov/test/services/localGit'>;
}
declare module 'codecov/test/services/semaphore.js' {
  declare module.exports: $Exports<'codecov/test/services/semaphore'>;
}
declare module 'codecov/test/services/shippable.js' {
  declare module.exports: $Exports<'codecov/test/services/shippable'>;
}
declare module 'codecov/test/services/snap.js' {
  declare module.exports: $Exports<'codecov/test/services/snap'>;
}
declare module 'codecov/test/services/travis.js' {
  declare module.exports: $Exports<'codecov/test/services/travis'>;
}
declare module 'codecov/test/services/wercker.js' {
  declare module.exports: $Exports<'codecov/test/services/wercker'>;
}
declare module 'codecov/test/upload.js' {
  declare module.exports: $Exports<'codecov/test/upload'>;
}
declare module 'codecov/testinit.js' {
  declare module.exports: $Exports<'codecov/testinit'>;
}
