// flow-typed signature: d610eea51b98a43ddc07b31057f40497
// flow-typed version: <<STUB>>/react-native-vector-icons_v^4.2.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-vector-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-vector-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-vector-icons/bin/generate-icon' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/bin/generate-material-icons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/Entypo' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/EvilIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/Feather' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/FontAwesome' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/Foundation' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/Ionicons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/lib/create-icon-set-from-fontello' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/lib/create-icon-set-from-icomoon' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/lib/create-icon-set' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/lib/generate-icon-set-from-css' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/lib/icon-button' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/lib/react-native' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/lib/react-native.osx' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/lib/tab-bar-item-ios' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/lib/toolbar-android' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/MaterialCommunityIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/MaterialIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/Octicons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/RNIMigration' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/SimpleLineIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/dist/Zocial' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Entypo' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/EvilIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Feather' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/FontAwesome' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Foundation' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Ionicons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/lib/create-icon-set-from-fontello' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/lib/create-icon-set-from-icomoon' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/lib/create-icon-set' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/lib/generate-icon-set-from-css' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/lib/icon-button' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/lib/react-native' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/lib/react-native.osx' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/lib/tab-bar-item-ios' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/lib/toolbar-android' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/MaterialCommunityIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/MaterialIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Octicons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/RNIMigration' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/SimpleLineIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Zocial' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-vector-icons/bin/generate-icon.js' {
  declare module.exports: $Exports<'react-native-vector-icons/bin/generate-icon'>;
}
declare module 'react-native-vector-icons/bin/generate-material-icons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/bin/generate-material-icons'>;
}
declare module 'react-native-vector-icons/dist/Entypo.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/Entypo'>;
}
declare module 'react-native-vector-icons/dist/EvilIcons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/EvilIcons'>;
}
declare module 'react-native-vector-icons/dist/Feather.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/Feather'>;
}
declare module 'react-native-vector-icons/dist/FontAwesome.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/FontAwesome'>;
}
declare module 'react-native-vector-icons/dist/Foundation.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/Foundation'>;
}
declare module 'react-native-vector-icons/dist/index.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/index'>;
}
declare module 'react-native-vector-icons/dist/Ionicons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/Ionicons'>;
}
declare module 'react-native-vector-icons/dist/lib/create-icon-set-from-fontello.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/lib/create-icon-set-from-fontello'>;
}
declare module 'react-native-vector-icons/dist/lib/create-icon-set-from-icomoon.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/lib/create-icon-set-from-icomoon'>;
}
declare module 'react-native-vector-icons/dist/lib/create-icon-set.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/lib/create-icon-set'>;
}
declare module 'react-native-vector-icons/dist/lib/generate-icon-set-from-css.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/lib/generate-icon-set-from-css'>;
}
declare module 'react-native-vector-icons/dist/lib/icon-button.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/lib/icon-button'>;
}
declare module 'react-native-vector-icons/dist/lib/react-native.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/lib/react-native'>;
}
declare module 'react-native-vector-icons/dist/lib/react-native.osx.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/lib/react-native.osx'>;
}
declare module 'react-native-vector-icons/dist/lib/tab-bar-item-ios.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/lib/tab-bar-item-ios'>;
}
declare module 'react-native-vector-icons/dist/lib/toolbar-android.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/lib/toolbar-android'>;
}
declare module 'react-native-vector-icons/dist/MaterialCommunityIcons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/MaterialCommunityIcons'>;
}
declare module 'react-native-vector-icons/dist/MaterialIcons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/MaterialIcons'>;
}
declare module 'react-native-vector-icons/dist/Octicons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/Octicons'>;
}
declare module 'react-native-vector-icons/dist/RNIMigration.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/RNIMigration'>;
}
declare module 'react-native-vector-icons/dist/SimpleLineIcons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/SimpleLineIcons'>;
}
declare module 'react-native-vector-icons/dist/Zocial.js' {
  declare module.exports: $Exports<'react-native-vector-icons/dist/Zocial'>;
}
declare module 'react-native-vector-icons/Entypo.js' {
  declare module.exports: $Exports<'react-native-vector-icons/Entypo'>;
}
declare module 'react-native-vector-icons/EvilIcons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/EvilIcons'>;
}
declare module 'react-native-vector-icons/Feather.js' {
  declare module.exports: $Exports<'react-native-vector-icons/Feather'>;
}
declare module 'react-native-vector-icons/FontAwesome.js' {
  declare module.exports: $Exports<'react-native-vector-icons/FontAwesome'>;
}
declare module 'react-native-vector-icons/Foundation.js' {
  declare module.exports: $Exports<'react-native-vector-icons/Foundation'>;
}
declare module 'react-native-vector-icons/index' {
  declare module.exports: $Exports<'react-native-vector-icons'>;
}
declare module 'react-native-vector-icons/index.js' {
  declare module.exports: $Exports<'react-native-vector-icons'>;
}
declare module 'react-native-vector-icons/Ionicons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/Ionicons'>;
}
declare module 'react-native-vector-icons/lib/create-icon-set-from-fontello.js' {
  declare module.exports: $Exports<'react-native-vector-icons/lib/create-icon-set-from-fontello'>;
}
declare module 'react-native-vector-icons/lib/create-icon-set-from-icomoon.js' {
  declare module.exports: $Exports<'react-native-vector-icons/lib/create-icon-set-from-icomoon'>;
}
declare module 'react-native-vector-icons/lib/create-icon-set.js' {
  declare module.exports: $Exports<'react-native-vector-icons/lib/create-icon-set'>;
}
declare module 'react-native-vector-icons/lib/generate-icon-set-from-css.js' {
  declare module.exports: $Exports<'react-native-vector-icons/lib/generate-icon-set-from-css'>;
}
declare module 'react-native-vector-icons/lib/icon-button.js' {
  declare module.exports: $Exports<'react-native-vector-icons/lib/icon-button'>;
}
declare module 'react-native-vector-icons/lib/react-native.js' {
  declare module.exports: $Exports<'react-native-vector-icons/lib/react-native'>;
}
declare module 'react-native-vector-icons/lib/react-native.osx.js' {
  declare module.exports: $Exports<'react-native-vector-icons/lib/react-native.osx'>;
}
declare module 'react-native-vector-icons/lib/tab-bar-item-ios.js' {
  declare module.exports: $Exports<'react-native-vector-icons/lib/tab-bar-item-ios'>;
}
declare module 'react-native-vector-icons/lib/toolbar-android.js' {
  declare module.exports: $Exports<'react-native-vector-icons/lib/toolbar-android'>;
}
declare module 'react-native-vector-icons/MaterialCommunityIcons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/MaterialCommunityIcons'>;
}
declare module 'react-native-vector-icons/MaterialIcons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/MaterialIcons'>;
}
declare module 'react-native-vector-icons/Octicons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/Octicons'>;
}
declare module 'react-native-vector-icons/RNIMigration.js' {
  declare module.exports: $Exports<'react-native-vector-icons/RNIMigration'>;
}
declare module 'react-native-vector-icons/SimpleLineIcons.js' {
  declare module.exports: $Exports<'react-native-vector-icons/SimpleLineIcons'>;
}
declare module 'react-native-vector-icons/Zocial.js' {
  declare module.exports: $Exports<'react-native-vector-icons/Zocial'>;
}
