// flow-typed signature: 9fca0611af059dd567467143c5d57f57
// flow-typed version: <<STUB>>/react-native-tab-view_v^0.0.70/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tab-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tab-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-tab-view/src/index' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/SceneMap' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabBar' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewAnimated' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewPagerAndroid' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewPagerPan' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewPagerScroll' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewTypeDefinitions' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TouchableItem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-tab-view/src/index.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/index'>;
}
declare module 'react-native-tab-view/src/SceneMap.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/SceneMap'>;
}
declare module 'react-native-tab-view/src/TabBar.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabBar'>;
}
declare module 'react-native-tab-view/src/TabViewAnimated.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewAnimated'>;
}
declare module 'react-native-tab-view/src/TabViewPagerAndroid.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewPagerAndroid'>;
}
declare module 'react-native-tab-view/src/TabViewPagerPan.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewPagerPan'>;
}
declare module 'react-native-tab-view/src/TabViewPagerScroll.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewPagerScroll'>;
}
declare module 'react-native-tab-view/src/TabViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewPropTypes'>;
}
declare module 'react-native-tab-view/src/TabViewTypeDefinitions.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewTypeDefinitions'>;
}
declare module 'react-native-tab-view/src/TouchableItem.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TouchableItem'>;
}
