// flow-typed signature: 12147d3a875d0a098b78e30bb9f97493
// flow-typed version: <<STUB>>/react-native-viewpager_v^0.2.13/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-viewpager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-viewpager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-viewpager/DefaultViewPageIndicator' {
  declare module.exports: any;
}

declare module 'react-native-viewpager/Sample/BottomScreen' {
  declare module.exports: any;
}

declare module 'react-native-viewpager/Sample/index.android' {
  declare module.exports: any;
}

declare module 'react-native-viewpager/Sample/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-viewpager/Sample/MainScreen' {
  declare module.exports: any;
}

declare module 'react-native-viewpager/Sample/SimpleScreen' {
  declare module.exports: any;
}

declare module 'react-native-viewpager/Sample/TopScreen' {
  declare module.exports: any;
}

declare module 'react-native-viewpager/ViewPager' {
  declare module.exports: any;
}

declare module 'react-native-viewpager/ViewPagerDataSource' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-viewpager/DefaultViewPageIndicator.js' {
  declare module.exports: $Exports<'react-native-viewpager/DefaultViewPageIndicator'>;
}
declare module 'react-native-viewpager/Sample/BottomScreen.js' {
  declare module.exports: $Exports<'react-native-viewpager/Sample/BottomScreen'>;
}
declare module 'react-native-viewpager/Sample/index.android.js' {
  declare module.exports: $Exports<'react-native-viewpager/Sample/index.android'>;
}
declare module 'react-native-viewpager/Sample/index.ios.js' {
  declare module.exports: $Exports<'react-native-viewpager/Sample/index.ios'>;
}
declare module 'react-native-viewpager/Sample/MainScreen.js' {
  declare module.exports: $Exports<'react-native-viewpager/Sample/MainScreen'>;
}
declare module 'react-native-viewpager/Sample/SimpleScreen.js' {
  declare module.exports: $Exports<'react-native-viewpager/Sample/SimpleScreen'>;
}
declare module 'react-native-viewpager/Sample/TopScreen.js' {
  declare module.exports: $Exports<'react-native-viewpager/Sample/TopScreen'>;
}
declare module 'react-native-viewpager/ViewPager.js' {
  declare module.exports: $Exports<'react-native-viewpager/ViewPager'>;
}
declare module 'react-native-viewpager/ViewPagerDataSource.js' {
  declare module.exports: $Exports<'react-native-viewpager/ViewPagerDataSource'>;
}
