// flow-typed signature: 61572aa770ba5ac00e420c269d8022af
// flow-typed version: <<STUB>>/react-native-drawer-layout_v^1.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-drawer-layout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-drawer-layout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-drawer-layout/dist/DrawerLayout.ios' {
  declare module.exports: any;
}

declare module 'react-native-drawer-layout/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-drawer-layout/dist/DrawerLayout.ios.js' {
  declare module.exports: $Exports<'react-native-drawer-layout/dist/DrawerLayout.ios'>;
}
declare module 'react-native-drawer-layout/dist/index.js' {
  declare module.exports: $Exports<'react-native-drawer-layout/dist/index'>;
}
