// flow-typed signature: 955a754c9cf0044960be869a6720689d
// flow-typed version: <<STUB>>/react-native-drawer-layout-polyfill_v^1.3.2/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-drawer-layout-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-drawer-layout-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-drawer-layout-polyfill/dist/index.android' {
  declare module.exports: any;
}

declare module 'react-native-drawer-layout-polyfill/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-drawer-layout-polyfill/dist/index.android.js' {
  declare module.exports: $Exports<'react-native-drawer-layout-polyfill/dist/index.android'>;
}
declare module 'react-native-drawer-layout-polyfill/dist/index.js' {
  declare module.exports: $Exports<'react-native-drawer-layout-polyfill/dist/index'>;
}
