/* @flow */

import type {
  NavigationSceneRendererProps,
  NavigationTransitionProps,
  NavigationTransitionSpec,
} from '../TypeDefinition';

import CardStackStyleInterpolator from './CardStackStyleInterpolator';
import HeaderStyleInterpolator from './HeaderStyleInterpolator';

import {
  Animated,
  Easing,
  Platform,
} from 'react-native';

/**
 * Describes a visual transition from one screen to another.
 */
export type TransitionConfig = {
  // The basics properties of the animation, such as duration and easing
  transitionSpec?: NavigationTransitionSpec,
  // How to animate position and opacity of the screen
  // based on the value generated by the transitionSpec
  screenInterpolator?: NavigationSceneRendererProps => Object,
};

// Used for all animations unless overriden
const DefaultTransitionSpec = ({
  // The following options are meant to mimic the nav animations of iOS 10
  duration: 250,
  timing: Animated.spring,
  bounciness: 0,
  speed: 9,
} : NavigationTransitionSpec);

// Standard iOS navigation transition
const SlideFromRightIOS = ({
  screenInterpolator: CardStackStyleInterpolator.forHorizontal,
} : TransitionConfig);

// Left To Right transition
const SlideLeftToRight = ({
  screenInterpolator: CardStackStyleInterpolator.leftToRight,
} : TransitionConfig);

// Top To Bottom transition
const SlideTopToBottom = ({
  screenInterpolator: CardStackStyleInterpolator.topToBottom,
} : TransitionConfig);

// Without transition
const SlideWithoutTransition = ({
  screenInterpolator: CardStackStyleInterpolator.slideWithoutTransition,
} : TransitionConfig);

// Standard iOS navigation transition for modals
const ModalSlideFromBottomIOS = ({
  screenInterpolator: CardStackStyleInterpolator.forVertical,
} : TransitionConfig);

// Standard Android navigation transition when opening an Activity
const FadeInFromBottomAndroid = ({
  // See http://androidxref.com/7.1.1_r6/xref/frameworks/base/core/res/res/anim/activity_open_enter.xml
  transitionSpec: {
    duration: 350,
    easing: Easing.out(Easing.poly(5)),  // decelerate
    timing: Animated.timing,
  },
  screenInterpolator: CardStackStyleInterpolator.forFadeFromBottomAndroid,
} : TransitionConfig);

// Standard Android navigation transition when closing an Activity
const FadeOutToBottomAndroid = ({
  // See http://androidxref.com/7.1.1_r6/xref/frameworks/base/core/res/res/anim/activity_close_exit.xml
  transitionSpec: {
    duration: 230,
    easing: Easing.in(Easing.poly(4)),  // accelerate
    timing: Animated.timing,
  },
  screenInterpolator: CardStackStyleInterpolator.forFadeFromBottomAndroid,
} : TransitionConfig);

function defaultTransitionConfig(
  // props for the new screen
  transitionProps: NavigationTransitionProps,
  // props for the old screen
  prevTransitionProps: NavigationTransitionProps,
  // default mode animate card
  mode: 'string',
  // if mode == 'modal' , default direction is vertical
  direction: 'string'
): TransitionConfig {

  if (
      mode === 'card' ||
      // Use default Android animation if direction is vertical and mode is modal
      (mode === 'modal' && direction === 'vertical' && Platform.OS === 'android') 
    ) {
    if (Platform.OS === 'android') {
      // Use the default Android animation no matter if the screen is a modal.
      // Android doesn't have full-screen modals like iOS does, it has dialogs.
      if (prevTransitionProps && (transitionProps.index < prevTransitionProps.index)) {
        // Navigating back to the previous screen
        return FadeOutToBottomAndroid;
      }
      return FadeInFromBottomAndroid;
    } else {
      // iOS and other platforms
      return SlideFromRightIOS;
    }
  } else {
    if(direction === 'horizontal') {
      return SlideFromRightIOS;
    } else if (direction === 'leftToRight') {
      return SlideLeftToRight;
    } else if (direction === 'topToBottom') {
      return SlideTopToBottom;
    } else if (direction === 'none') {
      return SlideWithoutTransition;
    }

    return ModalSlideFromBottomIOS;
    
  }
}

export default {
  DefaultTransitionSpec,
  defaultTransitionConfig,
};
