// flow-typed signature: c7c91558bdd879554405af715286a9e4
// flow-typed version: <<STUB>>/@expo/vector-icons_v^6.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@expo/vector-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@expo/vector-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@expo/vector-icons/createIconSet' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/createIconSetFromFontello' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/createIconSetFromIcoMoon' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Entypo' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/EvilIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Feather' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/FontAwesome' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Foundation' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/iconFontSources' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Ionicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/MaterialCommunityIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/MaterialIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Octicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/SimpleLineIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/Entypo' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/EvilIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/Feather' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/FontAwesome' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/Foundation' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/generate-icon' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/generate-material-icons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/index' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/Ionicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/create-icon-set-from-fontello' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/create-icon-set-from-icomoon' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/create-icon-set' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/generate-icon-set-from-css' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/icon-button' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/react-native' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/react-native.osx' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/tab-bar-item-ios' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/toolbar-android' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/MaterialCommunityIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/MaterialIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/Octicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/RNIMigration' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/SimpleLineIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/vendor/react-native-vector-icons/Zocial' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/website/err-if-inside-universe' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/website/src/App' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/website/src/Icon' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/website/src/IconConstants' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/website/src/IconList' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/website/src/index' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Zocial' {
  declare module.exports: any;
}

// Filename aliases
declare module '@expo/vector-icons/createIconSet.js' {
  declare module.exports: $Exports<'@expo/vector-icons/createIconSet'>;
}
declare module '@expo/vector-icons/createIconSetFromFontello.js' {
  declare module.exports: $Exports<'@expo/vector-icons/createIconSetFromFontello'>;
}
declare module '@expo/vector-icons/createIconSetFromIcoMoon.js' {
  declare module.exports: $Exports<'@expo/vector-icons/createIconSetFromIcoMoon'>;
}
declare module '@expo/vector-icons/Entypo.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Entypo'>;
}
declare module '@expo/vector-icons/EvilIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/EvilIcons'>;
}
declare module '@expo/vector-icons/Feather.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Feather'>;
}
declare module '@expo/vector-icons/FontAwesome.js' {
  declare module.exports: $Exports<'@expo/vector-icons/FontAwesome'>;
}
declare module '@expo/vector-icons/Foundation.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Foundation'>;
}
declare module '@expo/vector-icons/iconFontSources.js' {
  declare module.exports: $Exports<'@expo/vector-icons/iconFontSources'>;
}
declare module '@expo/vector-icons/index' {
  declare module.exports: $Exports<'@expo/vector-icons'>;
}
declare module '@expo/vector-icons/index.js' {
  declare module.exports: $Exports<'@expo/vector-icons'>;
}
declare module '@expo/vector-icons/Ionicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Ionicons'>;
}
declare module '@expo/vector-icons/MaterialCommunityIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/MaterialCommunityIcons'>;
}
declare module '@expo/vector-icons/MaterialIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/MaterialIcons'>;
}
declare module '@expo/vector-icons/Octicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Octicons'>;
}
declare module '@expo/vector-icons/SimpleLineIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/SimpleLineIcons'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/Entypo.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/Entypo'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/EvilIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/EvilIcons'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/Feather.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/Feather'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/FontAwesome.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/FontAwesome'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/Foundation.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/Foundation'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/generate-icon.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/generate-icon'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/generate-material-icons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/generate-material-icons'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/index.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/index'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/Ionicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/Ionicons'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/create-icon-set-from-fontello.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/lib/create-icon-set-from-fontello'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/create-icon-set-from-icomoon.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/lib/create-icon-set-from-icomoon'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/create-icon-set.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/lib/create-icon-set'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/generate-icon-set-from-css.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/lib/generate-icon-set-from-css'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/icon-button.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/lib/icon-button'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/react-native.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/lib/react-native'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/react-native.osx.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/lib/react-native.osx'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/tab-bar-item-ios.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/lib/tab-bar-item-ios'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/lib/toolbar-android.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/lib/toolbar-android'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/MaterialCommunityIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/MaterialCommunityIcons'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/MaterialIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/MaterialIcons'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/Octicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/Octicons'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/RNIMigration.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/RNIMigration'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/SimpleLineIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/SimpleLineIcons'>;
}
declare module '@expo/vector-icons/vendor/react-native-vector-icons/Zocial.js' {
  declare module.exports: $Exports<'@expo/vector-icons/vendor/react-native-vector-icons/Zocial'>;
}
declare module '@expo/vector-icons/website/err-if-inside-universe.js' {
  declare module.exports: $Exports<'@expo/vector-icons/website/err-if-inside-universe'>;
}
declare module '@expo/vector-icons/website/src/App.js' {
  declare module.exports: $Exports<'@expo/vector-icons/website/src/App'>;
}
declare module '@expo/vector-icons/website/src/Icon.js' {
  declare module.exports: $Exports<'@expo/vector-icons/website/src/Icon'>;
}
declare module '@expo/vector-icons/website/src/IconConstants.js' {
  declare module.exports: $Exports<'@expo/vector-icons/website/src/IconConstants'>;
}
declare module '@expo/vector-icons/website/src/IconList.js' {
  declare module.exports: $Exports<'@expo/vector-icons/website/src/IconList'>;
}
declare module '@expo/vector-icons/website/src/index.js' {
  declare module.exports: $Exports<'@expo/vector-icons/website/src/index'>;
}
declare module '@expo/vector-icons/Zocial.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Zocial'>;
}
