// flow-typed signature: 3bc29d2dec3d90d765e922c8096d8dfc
// flow-typed version: <<STUB>>/babel-plugin-syntax-object-rest-spread_v^6.13.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-syntax-object-rest-spread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-syntax-object-rest-spread' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-syntax-object-rest-spread/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-syntax-object-rest-spread/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-syntax-object-rest-spread/lib/index'>;
}
