// flow-typed signature: 7381ec0e475ad6658e39dd49d7a46956
// flow-typed version: <<STUB>>/react-native-safe-area-view_v^0.7.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safe-area-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safe-area-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-safe-area-view/index.web' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-view/withOrientation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-safe-area-view/index' {
  declare module.exports: $Exports<'react-native-safe-area-view'>;
}
declare module 'react-native-safe-area-view/index.js' {
  declare module.exports: $Exports<'react-native-safe-area-view'>;
}
declare module 'react-native-safe-area-view/index.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/index.web'>;
}
declare module 'react-native-safe-area-view/withOrientation.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/withOrientation'>;
}
