// flow-typed signature: 325e9512817177ae9b36a263c768921e
// flow-typed version: <<STUB>>/react-lifecycles-compat_v^1.0.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-lifecycles-compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-lifecycles-compat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-lifecycles-compat/react-lifecycles-compat' {
  declare module.exports: any;
}

declare module 'react-lifecycles-compat/react-lifecycles-compat.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-lifecycles-compat/index' {
  declare module.exports: $Exports<'react-lifecycles-compat'>;
}
declare module 'react-lifecycles-compat/index.js' {
  declare module.exports: $Exports<'react-lifecycles-compat'>;
}
declare module 'react-lifecycles-compat/react-lifecycles-compat.js' {
  declare module.exports: $Exports<'react-lifecycles-compat/react-lifecycles-compat'>;
}
declare module 'react-lifecycles-compat/react-lifecycles-compat.min.js' {
  declare module.exports: $Exports<'react-lifecycles-compat/react-lifecycles-compat.min'>;
}
