import { readFileSync, writeFileSync } from 'node:fs';
import { relative } from 'node:path';
import { fileURLToPath, URL } from 'node:url';

const root = new URL('..', import.meta.url);
const dest = new URL('example/src/sf-symbol-names.ts', root);

const types = readFileSync(
  new URL('node_modules/sf-symbols-typescript/dist/index.d.ts', root),
  'utf-8'
);

const symbolRegex = /^\s*\|\s*'([^']+)'/gm;
const symbols = new Set<string>();

let match;

while ((match = symbolRegex.exec(types)) !== null) {
  symbols.add(match[1]);
}

process.stdout.write(`Found ${symbols.size} SF Symbol names\n`);

writeFileSync(
  dest,
  `// Auto-generated by scripts/generate-sf-symbol-names.ts
// Do not edit manually

export const SF_SYMBOL_NAMES = [
${[...symbols]
  .sort()
  .map((s) => `  '${s}',`)
  .join('\n')}
] as const;
`,
  'utf-8'
);

process.stdout.write(
  `Wrote ${relative(fileURLToPath(root), fileURLToPath(dest))}\n`
);
