name: autofix.ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup
        uses: ./.github/actions/setup

      - name: Fix lint issues
        run: pnpm lint --fix

      - name: Autofix
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
