name: Comment on closed issue
on:
  issue_comment:
    types:
      - created

jobs:
  closed-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.state == 'closed' }}
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              const body = "Hey! This issue is closed and isn't watched by the core team. You are welcome to discuss the issue with others in this thread, but if you think this issue is still valid and needs to be tracked, please open a new issue with a repro.";

              const comments = await github.paginate(github.rest.issues.listComments, {
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });

              if (comments.some((comment) => comment.body === body)) {
                return;
              }

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body,
              });
